### ISSUE TITLE
quota exceeded

### ISSUE THREAD

**Issue by angladacamps** [gchokov/homebridge-foobot#11]
Hi,
I'm getting 'quota exceeded' error and i'v not received any data from Foobot till 48 hours ago...
I go to my foobot api account and it tells me 200/200 api calls today.. but sure I havent received any data from foobot. It always says '0% humidity' '0C temperature', and quota exceeded error in Homebridge log persists..

any chance it's plugin related issue?

**Comment by salmundo11** [comment]
I'm seeing quite a bit of this:

`Preparing Advertiser for 'Foobot 3746' using ciao backend!
Starting to advertise 'Foobot 3746' using ciao backend!
[2/28/2021, 3:59:53 PM] Homebridge v1.3.1 (Foobot) is running on port 60366.
[2/28/2021, 3:59:55 PM] [Foobot] Quota exceeded, consider refreshing less often
[2/28/2021, 3:59:55 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[2/28/2021, 3:59:56 PM] [homebridge-foobot] This plugin generated a warning from the characteristic 'Air Quality': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.

/usr/local/lib/node_modules/homebridge-foobot/index.js:600
                                        var peakCO2 = Math.max(...this.historicalmeasurements[4]);
                        ^
TypeError: this.historicalmeasurements[4] is not iterable (cannot read property undefined)
    at Foobot.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/index.js:600:25)
    at Foobot.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/index.js:488:12)
    at Foobot.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/index.js:198:6)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-foobot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
[2/28/2021, 3:59:57 PM] [Foobot] Child bridge process ended
[2/28/2021, 3:59:57 PM] [Foobot] Process Ended. Code: 1, Signal: null
[2/28/2021, 4:00:04 PM] [Foobot] Restarting Process...
Initializing HAP-NodeJS v0.9.2...
[2/28/2021, 4:00:05 PM] [Foobot] Launched external bridge with PID 13297
[2/28/2021, 4:00:05 PM] Registering accessory 'homebridge-foobot.Foobot'
[2/28/2021, 4:00:05 PM] [Foobot] Loaded homebridge-foobot v0.5.3 successfully
[2/28/2021, 4:00:05 PM] Loaded 0 cached accessories from cachedAccessories.F0FE6BCEDD60.
Loggine enabled
Preparing Advertiser for 'Foobot 3746' using ciao backend!
Starting to advertise 'Foobot 3746' using ciao backend!`

**Comment by salmundo11** [comment]
I'm seeing a similar issue:

[3/1/2021, 2:43:12 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 2:43:12 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 2:53:12 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 2:53:12 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:03:12 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:03:12 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:13:12 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:13:12 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:23:12 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:23:12 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:33:12 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:33:12 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:39:16 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:39:16 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:39:16 PM] [homebridge-foobot] This plugin generated a warning from the characteristic 'Air Quality': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[3/1/2021, 3:39:16 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:39:16 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:39:16 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:39:16 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:39:16 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:39:16 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:39:16 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:39:16 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:39:16 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:39:16 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[3/1/2021, 3:53:13 PM] [Foobot] Quota exceeded, consider refreshing less often
[3/1/2021, 3:53:13 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
