### ISSUE TITLE
 expected valid number and received NaN. TypeError: this.historicalmeasurements is not iterable (cannot read property undefined)

### ISSUE THREAD

**Issue by salmundo11** [gchokov/homebridge-foobot#13]
Preparing Advertiser for 'Foobot 3746' using ciao backend!
Starting to advertise 'Foobot 3746' using ciao backend!
[2/28/2021, 3:59:53 PM] Homebridge v1.3.1 (Foobot) is running on port 60366.
[2/28/2021, 3:59:55 PM] [Foobot] Quota exceeded, consider refreshing less often
[2/28/2021, 3:59:55 PM] [Foobot] Setting Sensors to 0 to continue bridge operation.
[2/28/2021, 3:59:56 PM] [homebridge-foobot] This plugin generated a warning from the characteristic 'Air Quality': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.

/usr/local/lib/node_modules/homebridge-foobot/index.js:600
                                        var peakCO2 = Math.max(...this.historicalmeasurements[4]);
                        ^
TypeError: this.historicalmeasurements[4] is not iterable (cannot read property undefined)
    at Foobot.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/index.js:600:25)
    at Foobot.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/index.js:488:12)
    at Foobot.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/index.js:198:6)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-foobot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
[2/28/2021, 3:59:57 PM] [Foobot] Child bridge process ended
[2/28/2021, 3:59:57 PM] [Foobot] Process Ended. Code: 1, Signal: null
[2/28/2021, 4:00:04 PM] [Foobot] Restarting Process...
Initializing HAP-NodeJS v0.9.2...
[2/28/2021, 4:00:05 PM] [Foobot] Launched external bridge with PID 13297
[2/28/2021, 4:00:05 PM] Registering accessory 'homebridge-foobot.Foobot'
[2/28/2021, 4:00:05 PM] [Foobot] Loaded homebridge-foobot v0.5.3 successfully

**Comment by keithws** [comment]
I'm seeing the same issue.
