### ISSUE TITLE
Datapoints: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gchokov** [gchokov/homebridge-foobot#8]
@iRonin we still run into problems with the response and the datapoints: 

/usr/lib/node_modules/homebridge-foobot/index.js:338
										else if (json.datapoints.length >= 1)
										                         ^

TypeError: Cannot read property 'length' of undefined
    at Foobot.<anonymous> (/usr/lib/node_modules/homebridge-foobot/index.js:338:36)
    at Foobot.<anonymous> (/usr/lib/node_modules/homebridge-foobot/index.js:198:6)

We have this above to prevent this: 
var noDataPoints = (json.datapoints === 'undefined');
										if (noDataPoints)
										{
											this.log.error('\x1b[36m%s\x1b[0m',"No datapoints in the response");
										}

But it doesn't handle the problem.
Do you have any idea what might be causing this? 

I can check this in about 2 weeks or so.. until then I have homebridge restarting with the help of pm2

**Comment by gchokov** [comment]
The problem occurs when Foobot is disconnected for more than a week from the network. Foobot API in this case doesn’t return any response.
